spring:
  profiles: pcf

gemfire_serverhost: 54.169.252.226
gemfire_serverport: 40404
db_url: jdbc:postgresql://54.169.252.226:10432/gpadmin
db_username: gpadmin
db_password: gpadmin
redis_host: redis-12631.c8.us-east-1-2.ec2.cloud.redislabs.com
redis_port: 12631
redis_password: RkugPJSJyuWiaCdm
